config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  scope "(:locale)", :locale => /en|ar/ do
    resources :articles

    resources :services
    resources :subservices

    resources :projects
    resources :subprojects
    resources :imports 
    get 'contact', to: 'contact#index'

  end

  root 'home#index'
  get '/:locale' => 'home#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true
  validates :summary, presence: true
  validates :text, presence: true

  translates :title, :text, :summary
  accepts_nested_attributes_for :translations, allow_destroy: true

  class Translation
    # define translation validations here
    validates :title, presence: true
    validates :summary, presence: true
    validates :text, presence: true
  end
  
  has_attached_file :asset, styles: { small: "360x220#", medium: "530x310#", large: "1150x500#" }
  validates_attachment_content_type :asset, :content_type => /\Aimage\/.*\Z/
  # add a delete_<asset_name> method:
  attr_accessor :delete_asset
  before_validation { self.asset.clear if self.delete_asset == '1' }
end

app/models/image.rb
class Image < ActiveRecord::Base

  has_attached_file :asset, styles: { small: "360x220#", medium: "530x310#", large: "1150x500#", square: "200x200#", small_rec: "250x270#" }
  validates_attachment_content_type :asset, :content_type => /\Aimage\/.*\Z/
  # add a delete_<asset_name> method:
  attr_accessor :delete_asset
  before_validation { self.asset.clear if self.delete_asset == '1' }

end

app/models/import.rb
class Import < ActiveRecord::Base

  translates :title, :text
  accepts_nested_attributes_for :translations, allow_destroy: true

  class Translation
    # define translation validations here
    validates :title, presence: true
    validates :text, presence: true
  end
end

app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :subservice
  translates :text
  accepts_nested_attributes_for :translations, allow_destroy: true

  class Translation
    # define translation validations here
    validates :text, presence: true
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :subprojects

  translates :title, :text
  accepts_nested_attributes_for :translations, allow_destroy: true

  class Translation
    # define translation validations here
    validates :title, presence: true
    validates :text, presence: true
  end
  
  has_attached_file :asset, styles: { small: "360x220#", medium: "530x310#", large: "1150x500#" }
  validates_attachment_content_type :asset, :content_type => /\Aimage\/.*\Z/
  # add a delete_<asset_name> method:
  attr_accessor :delete_asset
  before_validation { self.asset.clear if self.delete_asset == '1' }
end

app/models/service.rb
class Service < ActiveRecord::Base
  validates :title, presence: true
  validates :text, presence: true
  has_many :subservices
  has_many :images, dependent: :destroy


  translates :title, :text
  accepts_nested_attributes_for :translations, allow_destroy: true

  class Translation
    # define translation validations here
    validates :title, presence: true
    validates :text, presence: true
  end
  
  class Translation
    validates :title, presence: true
    validates :text, presence: true
  end

end

app/models/subproject.rb
class Subproject < ActiveRecord::Base
  belongs_to :project
  translates :title, :text
  accepts_nested_attributes_for :translations, allow_destroy: true

  has_attached_file :asset, styles: { small: "360x220#", medium: "530x310#", large: "1150x500#" }
  validates_attachment_content_type :asset, :content_type => /\Aimage\/.*\Z/
  # add a delete_<asset_name> method:
  attr_accessor :delete_asset
  before_validation { self.asset.clear if self.delete_asset == '1' }
  
  class Translation
    # define translation validations here
    validates :title, presence: true
    validates :text, presence: true
  end

end

app/models/subservice.rb
class Subservice < ActiveRecord::Base
  has_many :points
  validates :title, presence: true
  validates :text, presence: true
  belongs_to :service
  has_many :images

  translates :title, :text
  accepts_nested_attributes_for :translations, allow_destroy: true

  class Translation
    validates :title, presence: true
    validates :text, presence: true
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.order("created_at DESC").page(params[:page]).per(6)
  end

  def show
    @article = Article.find(params[:id])
  end



end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @articles = Article.last(3)
  end
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  def index
    @imports = Import.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
    @subprojects = Subproject.where(:bigProject => true).order("created_at DESC").page(params[:page]).per(4)
  end

  def show
    if (params[:id])
      @projects = Project.all
      @project = Project.find(params[:id])
      @subprojects = Subproject.where(project_id: @project.id).order("created_at DESC").page(params[:page]).per(4)
    else
      @projects = Project.all
      @subprojects = Subproject.where(:bigProject => true).order("created_at DESC").page(params[:page]).per(4)
    end
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def show
    @service = Service.find(params[:id])
    @subservices = @service.subservices.all
    @services = Service.all
    @images = Image.where(service_id: @service.id).all
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/subservices_helper.rb
module SubservicesHelper
end

app/views/contact/index.html.erb
<section>
  <div class="map">
    <div id="google-map" class="map_model" data-zoom="16"></div>
    <ul class="map_locations">

      <li data-x="31.2434494" data-y="30.0510643" data-basic="/assets/gmap_marker.png" data-active="/assets/gmap_marker_active.png">
        <p>
          <%= t :address_text %> <br/>
          <span><%= t :telephone_text %> </span>
        </p>
      </li>
    </ul>
  </div>
</section>

<section class="well well7 wow fadeInLeft">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-xs-12">
        <h3 class="text-center">
          <%= t :address %>
        </h3>
        <address class="h6">
          <%= t :address_text %>
        </address>
        <br>
        <address class="addr1">

          <dl>
            <dt><%= t :telephone %></dt>
            <dd>
              <a href='callto:#'>
                <%= t :telephone_text %></a>
            </dd>
            <dt></dt>
            <dd>
              <a href='callto:#'>
                <%= t :telephone_text1 %></a>
            </dd>
            <dt>
              <dd></dd>
            </dt>
            <dt><%= t :fax %></dt>
            <dd>
              <a href='callto:#'>
                <%= t :fax_telex_text %></a>
            </dd>
            <dt>
              <dd></dd>
            </dt>
            <dt><%= t :telex %></dt>
            <dd>
              <a href='callto:#'>
                <%= t :fax_telex_text1 %></a>
            </dd>
          </dl>
          <dl>
            <dt><%= t :email %></dt>
            <dd class="mail">
              <a href="mailto:#">info@elfoulycompany.com</a>
            </dd>
            <dt>
              <dd class="mail">elfoulycompany.com</a>
              </dd>
            </dt>
          </dl>
        </address>
      </div>

      <div class="col-md-8 col-xs-12 wow fadeInRight">
        <h3 class="text-center">
          <%= t :nav_contact %>
        </h3>

        <form class='mailform' method="post" action="bat/rd-mailform.php" data-type="contact">
          <div class="form-group name" data-add-placeholder>
            <label for="mailform-input-name"><%= t :your_name %></label>
            <input id="mailform-input-name" type="text" name="name" data-constraints="@LettersOnly @NotEmpty"/>
          </div>

          <div class="form-group" data-add-placeholder>
            <label for="mailform-input-email"><%= t :your_email %></label>
            <input id="mailform-input-email" type="text" name="email" data-constraints="@Email @NotEmpty"/>
          </div>

          <div class="form-group" data-add-placeholder>
            <label for="mailform-input-phone"><%= t :your_phone %></label>
            <input id="mailform-input-phone" type="text" name="phone" data-constraints="@Phone"/>
          </div>

          <div class="form-group textarea" data-add-placeholder>
            <label for="mailform-input-textarea"><%= t :your_message %></label>
            <textarea id="mailform-input-textarea" name="message" data-constraints="@NotEmpty"></textarea>
          </div>

          <div class="form-group btn-wr">
            <button class="btn btn-default" type="submit"><%= t :submit_message %></button>
          </div>
        </form>

      </div>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<section class="camera_container">
  <div class="jumbotron text-center">
    <div class="container">
      <% if I18n.locale == I18n.default_locale %>
        <p class="head">
          <%= t :jumbo1 %>
          <span>
            <%= t :jumbo2 %>
          </span>
        </p>
      <% else %>
      <p class="head" style="font-size:77px">
        <%= t :jumbo1 %>
        <span style="font-size:60px">
          <%= t :jumbo2 %>
        </span>
      </p>
      <%end%>
    </div>
  </div>
  <div id="camera" class="camera_wrap">
    <div data-src="/assets/slide3.jpg">
      <div class="camera_caption fadeIn"></div>
    </div>
    <div data-src="/assets/slide2.jpg">
      <div class="camera_caption fadeIn"></div>
    </div>
    <div data-src="/assets/slide1.jpg">
      <div class="camera_caption fadeIn"></div>
    </div>
  </div>
</section>


<section class="well well1">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6 col-xs-6 wow fadeInLeft" data-wow-delay=".9s"  style="text-align: center;">
        <img src="/assets/page-1_img1.png" alt=""/>
        <h5 class="text-center" >
          <%= t :project_managment %>
        </h5>

        <p class="txt-light text-center">
          <%= t :project_managment_text %>
        </p>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-6 wow fadeInLeft" data-wow-delay=".7s"  style="text-align: center;">

        <img src="/assets/page-1_img4.png" alt=""/>
        <h5 class="text-center">
          <%= t :inovations %>
        </h5>

        <p class="txt-light text-center">
          <%= t :inovations_text %>
        </p>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-6 wow fadeInLeft" data-wow-delay=".5s"  style="text-align: center;">

        <img src="/assets/impexp.png" alt=""/>
        <h5 class="text-center">
          <%= t :imp_exp %>
        </h5>

        <p class="txt-light text-center">
          <%= t :imp_exp_text %>
        </p>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-6 wow fadeInLeft" data-wow-delay=".3s"  style="text-align: center;">

        <img src="/assets/page-1_img2.png" alt=""/>
        <h5 class="text-center">
          <%= t :inspection %>
        </h5>

        <p class="txt-light text-center">
          <%= t :inspection_text %>
        </p>
      </div>
    </div>
  </div>
</section>

<section class="well well2 parallax text-center" data-url="/assets/parallax1.jpg" data-mobile="true" data-speed="0.6">
  <div class="container">
    <h2 class="fw-l arabic_xl">
      <%= t :our_history %>
    </h2>
    <p class="white ins1 offs1">
      <%= t :our_history_text %>
    </p>
  </div>
</section>

<section class="ang_block bg-primary text-center wow fadeIn" data-wow-duration="1.5s">
  <div class="container" id="home_numbers">
    <div class="row">

      <div class="col-md-3 col-sm-3 col-xs-6">
        <em>
          10
        </em>
        <p>
          <%= t :engineers %>
        </p>
      </div>

      <div class="col-md-3 col-sm-3 col-xs-6">
        <em>
          90
        </em>
        <p>
          <%= t :technicians %>
        </p>
      </div>

      <div class="col-md-3 col-sm-3 col-xs-6">
        <em>
          5
        </em>
        <p>
          <%= t :foremen %>
        </p>
      </div>

      <div class="col-md-3 col-sm-3 col-xs-6">
        <em>
          15
        </em>
        <p>
          <%= t :admin_financing %>
        </p>
      </div>

    </div>
  </div>
</section>

  <section class="well well3">
    <div class="container">
      <h3 class="text-center arabic_lg">
        <%= t :latest_news %>
      </h3>

      <div class="row">
        <% @articles.each do |a| %>
          <div class="col-md-4 col-sm-6 col-xs-12" >
            <div class="thumbnail thumbnail4">
              <img src="<%= a.asset.url(:small) %>" alt="">

              <div class="caption">
                <h6 class="arabic_md">
                  <%= link_to a.title, article_path(a) %>
                </h6>

                <p class="arabic_xs">
                  <%= a.summary %>
                </p>

              </div>
            </div>
          </div>
        <% end %>
      </div>
      </div>
    </div>
  </section>

  <div class="map">
    <div id="google-map" class="map_model" data-zoom="16"></div>
    <ul class="map_locations">

      <li data-x="31.2434494" data-y="30.0510643" data-basic="/assets/gmap_marker.png" data-active="/assets/gmap_marker_active.png">
        <p>
          <%= t :address_text %> <br/>
          <span><%= t :telephone_text %> </span>
        </p>
      </li>
    </ul>
  </div>